### ISSUE TITLE
`namespace` required in this module, however, optional in many others.

### ISSUE THREAD

**Issue by davidjeddy** [cloudposse/terraform-aws-cloudwatch-agent#5]
First off, thank you very much for making so much effort open source and available to the public. I have been able to accomplish in a week what took 6 months originally thanks to your library of modules. 

On to the issue at hand; in many / most of the modules the `namespace` variable is optional. However in this module it is required. Request: allow `namespace` to be optional in this module.

**Comment by parabolic** [comment]
Hi @davidjeddy , sorry for not replying earlier but I am guessing the notification fell under my radar. 
Do you still need this, in any case I will see that this module is updated with the latest versions, including TF 0.12.

**Comment by davidjeddy** [comment]
It is not critical; but would be nice for consistency sake.
